# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UM4W83zlp18nk_1k9DSdBe_Q9Jh3WYf8
"""

# Sistema UniCesumar Parking - MAPA
def calcular_estacionamento():
    # Variáveis para controle do administrador
    total_arrecadado = 0.0
    qtd_motos = 0
    qtd_carros = 0
    qtd_camionetes = 0
    qtd_isentos = 0

    print("--- Bem-vindo ao Sistema UniCesumar Parking ---")

    while True:
        print("\nNovo atendimento (ou digite 'sair' no tipo de veiculo para encerrar)")

        # Entrada do tipo de veículo
        tipo = input("Tipo do veículo (motocicleta, carro, camionete): ").lower()

        if tipo == 'sair':
            break

        # Entrada do tempo de permanência
        try:
            minutos = int(input("Tempo de permanência em minutos: "))
        except ValueError:
            print("Por favor, digite um número válido.")
            continue

        # Lógica de cobrança conforme a tabela do MAPA
        valor_pagar = 0.0

        if minutos <= 15:
            valor_pagar = 0.0
            qtd_isentos += 1
            print("Status: ISENTO")
        elif minutos <= 60:
            valor_pagar = 1.50
        else:
            # R$ 1,50 pela primeira hora + R$ 1,00 por hora adicional
            # O cálculo usa (minutos - 1) // 60 para cobrar a cada hora iniciada
            horas_adicionais = (minutos - 1) // 60
            valor_pagar = 1.50 + (horas_adicionais * 1.00)

        # Atualização dos dados do administrador
        total_arrecadado += valor_pagar

        if tipo == "motocicleta":
            qtd_motos += 1
        elif tipo == "carro":
            qtd_carros += 1
        elif tipo == "camionete":
            qtd_camionetes += 1

        print(f"Valor a pagar: R$ {valor_pagar:.2f}")

    # Relatório Final para o Administrador
    print("\n--- RELATÓRIO DIÁRIO ---")
    print(f"Total arrecadado: R$ {total_arrecadado:.2f}")
    print(f"Veículos isentos: {qtd_isentos}")
    print(f"Quantidade de Motocicletas: {qtd_motos}")
    print(f"Quantidade de Carros: {qtd_carros}")
    print(f"Quantidade de Camionetes: {qtd_camionetes}")

# Executa o sistema
calcular_estacionamento()
